apiVersion: v1
kind: Namespace
metadata:
  name: knative-serving
---
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  # additionalManifests:
  #   - "https://github.com/knative/serving/releases/download/knative-v1.21.2/serving-default-domain.yaml"
  deployments:
    - name: controller
      env:
        - container: controller
          envVars:
            - name: KUBERNETES_MIN_VERSION
              value: "v1.25.0"
    - name: autoscaler
      env:
        - container: autoscaler
          envVars:
            - name: KUBERNETES_MIN_VERSION
              value: "v1.25.0"
    - name: activator
      env:
        - container: activator
          envVars:
            - name: KUBERNETES_MIN_VERSION
              value: "v1.25.0"
    - name: webhook
      env:
        - container: webhook
          envVars:
            - name: KUBERNETES_MIN_VERSION
              value: "v1.25.0"
    - name: autoscaler-hpa
      env:
        - container: autoscaler-hpa
          envVars:
            - name: KUBERNETES_MIN_VERSION
              value: "v1.25.0"
    - name: net-kourier-controller
      env:
        - container: controller
          envVars:
            - name: KUBERNETES_MIN_VERSION
              value: "v1.25.0"
    - name: 3scale-kourier-gateway
      env:
        - container: kourier-gateway
          envVars:
            - name: KUBERNETES_MIN_VERSION
              value: "v1.25.0"
  ingress:
    kourier:
      enabled: true
  config:
    network:
      ingress-class: "kourier.ingress.networking.knative.dev"
# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: knative-eventing
# ---
# apiVersion: operator.knative.dev/v1beta1
# kind: KnativeEventing
# metadata:
#   name: knative-eventing
#   namespace: knative-eventing
