apiVersion: v1
kind: Secret
metadata:
  name: kyverno-ingress-tls
  namespace: app-ns
data:
  tls.crt: >-
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQVENDQWlXZ0F3SUJBZ0lVZUt2aE4xaE00S0N6TVBmSXR2WUp4Z3lyUitvd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0hqRWNNQm9HQTFVRUF3d1RhM2wyWlhKdWJ5NTNaV0pvYjI5ckxtTnZiVEFlRncweU5qQTBNVFV3TVRNegpNVEZhRncweU56QTBNVFV3TVRNek1URmFNQjR4SERBYUJnTlZCQU1NRTJ0NWRtVnlibTh1ZDJWaWFHOXZheTVqCmIyMHdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFET0tVazRKM1ZXRGlWYzM4emEKUUFoMFlvUUZvcWpndjlieVJsVjlUZ2h0QnFxd3BKMW1qa2gwN0ZZcjZ0RnNvTEVQYnY4b3dDYURZSmdUZ01XMApDY0oxQXBkazVmdlkyeVJtRGt2VHlZMjljaWtPZ0V2bXYyZStSczFnUTU4TzU4M29Pa2RjQ09keFQrVERMaGJqCnRNdlV1Y091VjQ0V0lyVFJadVRkQys3Z0g5eXdpaEovc1huN2ltcFNOWjJUNjlLNkRtLy9kSkNFNDZWNWdra2cKR3B5Z1M0U1dxTkwzVnhORlV3dDRwY0M2cVNNaWtoYW1CT1ZnVFEzL3pnT2V1TWxUWG02cXA4YnpNYlF0eDZxdwpxVmxTbjRkNjEzRmFQSmp3Z0dtczI2MDZVR3F4R09ReXVVY0RlNkJlYVozOWJwbW1jREQ5VDR2eDY0U3I2Ull6ClZQSnBBZ01CQUFHamN6QnhNQjBHQTFVZERnUVdCQlRoNG5MNUJoZWNGYzlWQnBndFpob0NOT3pBZ2pBZkJnTlYKSFNNRUdEQVdnQlRoNG5MNUJoZWNGYzlWQnBndFpob0NOT3pBZ2pBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUI0RwpBMVVkRVFRWE1CV0NFMnQ1ZG1WeWJtOHVkMlZpYUc5dmF5NWpiMjB3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCCkFFRWxYbVFwRG04b1dhNTA5cjRpemtKd0c0WWU0UEt1Rktab3BPVEw3T0FQZUpYMlhyU0tuaGVMTzJmK1BpczIKcXFySWk3WTVaZlF0UGp0S3VPdFB1ZFR6TENBdFlDZlBWdVhhUzBjck1acXY0YzJ3bnZ4NkhIRStodk9nRFVicApORG8xMEY5anlnMlk0cng4a0VqTENCVHhxYW9EelN2ZmdFOC9pbkM1VTNyOXRBeDFvVlBxNEIzOFQzcWduVnNOCnBzQXhVT3ZTODlKZjlzVzdrS0Iyalp2Q1NPdGxlbk5kdEg3Zm5FbmlDNHhjRG1OWUNrWGJua2NYcEhDYVI5OUYKVi9WNG5xK0FwanZMOXFGOGdBK3VjTzBEUG00c1krTm80d296MzJiK0tJYW5qMzZlL1JZTkV5cVZwVzlqOHVPdQpLL0lHSTI1MkYwUHpIR2lLbTJKd3JqOD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: >-
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRRE9LVWs0SjNWV0RpVmMKMzh6YVFBaDBZb1FGb3FqZ3Y5YnlSbFY5VGdodEJxcXdwSjFtamtoMDdGWXI2dEZzb0xFUGJ2OG93Q2FEWUpnVApnTVcwQ2NKMUFwZGs1ZnZZMnlSbURrdlR5WTI5Y2lrT2dFdm12MmUrUnMxZ1E1OE81ODNvT2tkY0NPZHhUK1RECkxoYmp0TXZVdWNPdVY0NFdJclRSWnVUZEMrN2dIOXl3aWhKL3NYbjdpbXBTTloyVDY5SzZEbS8vZEpDRTQ2VjUKZ2trZ0dweWdTNFNXcU5MM1Z4TkZVd3Q0cGNDNnFTTWlraGFtQk9WZ1RRMy96Z09ldU1sVFhtNnFwOGJ6TWJRdAp4NnF3cVZsU240ZDYxM0ZhUEpqd2dHbXMyNjA2VUdxeEdPUXl1VWNEZTZCZWFaMzlicG1tY0REOVQ0dng2NFNyCjZSWXpWUEpwQWdNQkFBRUNnZ0VBQVlJZXdrQUFtQTN2UTNTQjB6b0FXWmtwQ0ZmZ0ExenRXZkpwcW9iWVJVb0wKbStGM2ZaRzFDUERISFJZVTQzTTEvQ3o2MU14Znl0RTFyMklqQ0o1WGl2c0ZWL0VhVk9JOG5RMld5QlBTcDNoWApkbEhCbmtpN25kMkY2ei8zS2p2ZW9ERTBCTTBlN3kzU0tZU1N2dUtzZjQ3c0lXWDlEb3FqREp4d3Y5b3ljRkZ2CmhuQWtUNDRUOTNJbVhUTFRHRmYyK2RFYmhtaFRIMmpWT3hQdVBPMWFoM05KOENDKzZoRHNMcUxkTmI3TmJ0MFcKTjlmdnJjdjVzUGVEZnVpbHRvbmdqZVN1dzRnaS9UWXNIWnhBc1FYc0kwZFhYQVJsN0hhRHJVSDEzOWRFVHBaUQpoUGsybFQxRmUrSTloTEFQQTJ5eWQzQXVJWmxNdSt6d2dMeHJQTzVaelFLQmdRRG50czQ1QmZiSDBGTTNOQ0pwCk1GcUwvU1YvT2JtQXgrcW1kdGE4Rkhud0VCL0lxN0VqWXBocUhibk15Mm5mSjdKZW5WTU9laEpWalNsTnMvSDQKS1pIb3VycUZwWHhlR1VDS1F3Ky9MeEprWlVvRjVRUDJLVWxFOXpwZldpYTZUWnBjWGhwZXp6OHlSMkozaTIyVwoxNHdZUHFWNjExZzlzaS8zckxIZnpQeWpCd0tCZ1FEanhOMW1uODZjd0lhcXlBTklEZU5jZG5OVGxrcTNzRTdOCjM5ajhUWVNpbGd3R2VkRzVNcWNwUjhRcW1KL0pVVXZ1aElrZ0R0eFE4bS83RGJEdnFFQVVRZ3k5K05rb29FbFcKWVQydDFRNW9GWWZiVUFzS2ExcVZRKzhJNCtQQ3l1WTFoZ3hMVzVQRFJxQW5HcEZIQmdFSFVQVi9oZ2ZHRXA0bApEaTBFMzBzekR3S0JnRzVsY2l0STVDS2U1b2JPbC9aMXl5NFhGZDVmcWpucEJhcjV3NlVvUEZCYjNrakZSRWdQCm1YNDFXMmh2SWFub1I5czhLVzRrU3NmbjBWM3I5Y1MrU1g0UU9QMmpzblZDb3JVODdpdXdTWnI3aHlEMzA4TmMKT0VSYlpidzRQMnRUdmM5MEppdzFvVzViQkZiZ1h2NFhBL0FwS0w0MkN4eVo0TENuM3JjNStzUFJBb0dCQU4rSQpUemp1VVZscFlVQ3VOdm82Rnc2aGVTRnBlRDY2R3p6VkdTRFQrdjJOZ0pQQ2JsN3hKVGpRSStjaURuOEcrQnhICm1rUUtFWktudTlxSlgwSjB2eDZpaTlyTkpHSkluSERYMGk2TjBDdTZKYkRJNTJ6OFd0UHU3ZUt0dE5OeFNXangKKzVMaGR5eklYVmpETEJ5bCtkQnlWZDBuYnUyblMrbFY5ankzNEJkbEFvR0FOQkNXQThneDdRdHk5eC9jOGJmRgpCT1pPZTdmb0k0OWlNQ0h3VmRSdXhnaENudXpTc0wvajQ4cnRVWTN0RWt2OUhLczVZYmJNVnpkeHlxTDU2cDEwCklXQjNtMGY5OFEyamdzcjg0dm12UlFycU94Z0EvS2FScDJLZHhSRlh6RlZ3T2lLK3orNmFXQ1ZZZFZtTy81M1EKUG1MdFIzeEZQcWJaV3F2WkFnaU5xb009Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
type: kubernetes.io/tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kyverno-ingress
  namespace: app-ns
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    # nginx.ingress.kubernetes.io/auth-type: basic
    # nginx.ingress.kubernetes.io/auth-secret: basic-auth-app-cluster
    # nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - kyverno.webhook.com
    secretName: kyverno-ingress-tls
  rules:
  - host: kyverno.webhook.com
    http:
      paths:
      - path: /app-ns/app-cluster(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: kyverno-svc
            port:
              number: 443
