apiVersion: v1
kind: Secret
metadata:
  name: cosign-key
  namespace: harbor-webhook
  labels:
    app: harbor-webhook-signer
type: Opaque
stringData:
  cosign.pub: |
    -----BEGIN PUBLIC KEY-----
    MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEOwZ7jA0sPg5JNOgzL3KZQjPaAqMp
    b04wySMlzdP5V7mZalfYBCpgAfgJYz8fvznZdFfSrA6XdawAZLn0xxFAoQ==
    -----END PUBLIC KEY-----
  cosign.key: |
    -----BEGIN ENCRYPTED SIGSTORE PRIVATE KEY-----
    eyJrZGYiOnsibmFtZSI6InNjcnlwdCIsInBhcmFtcyI6eyJOIjo2NTUzNiwiciI6
    OCwicCI6MX0sInNhbHQiOiIxSDgzeHQrNTNrcUprc3ZIUndXNWFTc0gvRVJGZEw3
    Zlp1RU81SFZIVm1ZPSJ9LCJjaXBoZXIiOnsibmFtZSI6Im5hY2wvc2VjcmV0Ym94
    Iiwibm9uY2UiOiJYeUFvV2owTFBrNEpEdjAwZ0hvaWhkeHFYbWdEbDY4RSJ9LCJj
    aXBoZXJ0ZXh0IjoiblBMUStjRnY1bUlRbEhMdlRTSmNtbi9lZ01iazNpd0F4cm9w
    NUkvd28zQTZHT0VVdUtDdVdGY0R3NjVFSkEvbmVYU2hzM0htOXZFMFNrMGdYbXRS
    dk83UExYR2d2NDhGVnJXZWt0Wml6WTN3L2s2enJqemZXdWdsTyswVXZFRDF1SGox
    Vlo4RGU0d08vcUN1SzBhdkFUdytOQkxsQVFxV0lqTTdVb3FXU1B0Z01XUzNpTlpi
    d1JLRm5tNTQwcWp2eTU4c2ZzRUpLQURBWVE9PSJ9
    -----END ENCRYPTED SIGSTORE PRIVATE KEY-----
  cosign.password: "123"
---
apiVersion: v1
kind: Secret
metadata:
  name: webhook-secret
  namespace: harbor-webhook
  labels:
    app: harbor-webhook-signer
type: Opaque
stringData:
  token: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  namespace: harbor-webhook
  labels:
    app: harbor-webhook-signer
type: Opaque
stringData:
  username: "admin"
  password: "Harbor12345"
