apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-webhook-config
  namespace: harbor-webhook
  labels:
    app: harbor-webhook-signer
data:
  ALLOWED_MAX_SEVERITY: "High,Medium,Low,Unknown,None"
  PORT: "8080"
  SKIP_OPERATORS: ""
  COSIGN_KEY_PATH: "/keys/cosign.key"
  REKOR_URL: ""
  FULCIO_URL: ""
  # Levels: DEBUG | INFO | WARN | ERROR
  LOG_LEVEL: "INFO"
  TLOG_DISABLED: "true"
  REGISTRY_INSECURE: "true"
