apiVersion: v1
kind: ServiceAccount
metadata:
  name: kyverno-app-cluster
  namespace: app-ns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kyverno-app-cluster
subjects:
  - kind: ServiceAccount
    name: kyverno-app-cluster
    namespace: app-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kyverno:app-cluster
---
apiVersion: v1
kind: Secret
metadata:
  name: kyverno-app-cluster
  namespace: app-ns
  annotations:
    kubernetes.io/service-account.name: kyverno-app-cluster
type: kubernetes.io/service-account-token